### ISSUE TITLE
[Feature Request] Right click -> Copy Time

### ISSUE THREAD

**Issue by BeanBagKing** [EricZimmerman/timeapp#2]
I'd love to be able to quickly copy the time something happened at, for making notes while mocking up something in a lab for example. I'm not sure what the best way to implement this would be, but I imagine either being able to right click on The time screen and selecting "Copy Local" or "Copy UTC". Or just right clicking directly on Local or UTC automatically copies that timestamp, at the time of the click, to the clipboard (faster than a menu, probably what I would prefer).

**Comment by EricZimmerman** [comment]
I would probably just go with double clicking the label or the time itself to copy the timestamp to your clipboard

**Comment by BeanBagKing** [comment]
Feel like I tried everything except that. Thank you. Self-closing as feature already exists.

**Comment by EricZimmerman** [comment]
it does? i surprise myself sometimes hehe
